services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cart
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  products-service:
    build: ./products-service
    container_name: products-service
    env_file: ./products-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/"]
      interval: 10s
      timeout: 3s
      retries: 10

  cart-service:
    build: ./cart-service
    container_name: cart-service
    env_file: ./cart-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/"]
      interval: 10s
      timeout: 3s
      retries: 10

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file: ./api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      products-service:
        condition: service_healthy
      cart-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  mongo_data:
  pg_data: